/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTotalsRouteImport } from './routes/_app/totals'
import { Route as AppJamaRouteImport } from './routes/_app/jama'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTotalsRoute = AppTotalsRouteImport.update({
  id: '/totals',
  path: '/totals',
  getParentRoute: () => AppRoute,
} as any)
const AppJamaRoute = AppJamaRouteImport.update({
  id: '/jama',
  path: '/jama',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/jama': typeof AppJamaRoute
  '/totals': typeof AppTotalsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/jama': typeof AppJamaRoute
  '/totals': typeof AppTotalsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/jama': typeof AppJamaRoute
  '/_app/totals': typeof AppTotalsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/calendar' | '/jama' | '/totals'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/calendar' | '/jama' | '/totals' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/calendar'
    | '/_app/jama'
    | '/_app/totals'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/totals': {
      id: '/_app/totals'
      path: '/totals'
      fullPath: '/totals'
      preLoaderRoute: typeof AppTotalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jama': {
      id: '/_app/jama'
      path: '/jama'
      fullPath: '/jama'
      preLoaderRoute: typeof AppJamaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppJamaRoute: typeof AppJamaRoute
  AppTotalsRoute: typeof AppTotalsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppJamaRoute: AppJamaRoute,
  AppTotalsRoute: AppTotalsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
